version: "3.5"

services:
    frontend:
        image: frontend
        environment:
            - API_URL=http://localhost/api/
    
    backend:
        image: backend
        environment:
            - REDIS=redis
            - FRONT_URL=http://localhost/
            - DB_USERNAME=myuser
            - DB_PASSWORD=mypass
            - DB_NAME=dbname
            - DB_HOST=db
        depends_on: 
            - db

    redis:
        image: redis
        volumes:
            - ./redis-store:/data:rw
        entrypoint: redis-server --appendonly yes
        restart: unless-stopped
    
    
    db:
        image: postgres
        restart: unless-stopped
        volumes:
            - database:/var/lib/postgresql/data
        environment:
          POSTGRES_PASSWORD: mypass
          POSTGRES_USER: myuser
          POSTGRES_DB: dbname
        container_name: db
    
    nginx:
        image: nginx
        restart: unless-stopped
        ports: 
          - 80:80
        expose: 
          - 80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
    database:
       
